version: 2
updates:
  - package-ecosystem: npm
    directory: "/presentation"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
  - package-ecosystem: nuget
    directory: "/code"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    groups:
      akka:
        patterns:
          - "Akka*"
